site_name: Over the Wire

copyright: 'Copyright &copy; 2019 Patrick M. Elsen'

repo_name: 'xfbs/otw'
repo_url: 'https://github.com/xfbs/otw'

theme:
  name: 'material'
  palette:
    primary: 'blue grey'
    accent: 'blue'
  logo:
    icon: 'security'
  feature:
    tabs: true

markdown_extensions:
  - extra
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

nav:
  - Overview: index.md
  - Bandit:
    - Overview: bandit/index.md
    - Level 0: bandit/level0.md
    - Level 1: bandit/level1.md
    - Level 2: bandit/level2.md
    - Level 3: bandit/level3.md
    - Level 4: bandit/level4.md
    - Level 5: bandit/level5.md
    - Level 6: bandit/level6.md
    - Level 7: bandit/level7.md
    - Level 8: bandit/level8.md
    - Level 9: bandit/level9.md
    - Level 10: bandit/level10.md
    - Level 11: bandit/level11.md
    - Level 12: bandit/level12.md
    - Level 13: bandit/level13.md
    - Level 14: bandit/level14.md
    - Level 15: bandit/level15.md
    - Level 16: bandit/level16.md
    - Level 17: bandit/level17.md
    - Level 18: bandit/level18.md
    - Level 19: bandit/level19.md
    - Level 20: bandit/level20.md
    - Level 21: bandit/level21.md
    - Level 22: bandit/level22.md
    - Level 23: bandit/level23.md
    - Level 24: bandit/level24.md
    - Level 25: bandit/level25.md
    - Level 26: bandit/level26.md
    - Level 27: bandit/level27.md
    - Level 28: bandit/level28.md
    - Level 29: bandit/level29.md
    - Level 30: bandit/level30.md
    - Level 31: bandit/level31.md
    - Level 32: bandit/level32.md
    - Level 33: bandit/level33.md
