site_name: Over the Wire

copyright: 'Copyright &copy; 2019 Patrick M. Elsen'

repo_name: 'xfbs/otw'
repo_url: 'https://github.com/xfbs/otw'

theme:
  name: 'material'
  palette:
    primary: 'blue grey'
    accent: 'blue'
  logo:
    icon: 'security'
  feature:
    tabs: true

markdown_extensions:
  - extra
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

nav:
  - Overview: index.md
  - Bandit:
    - Overview: bandit/index.md
    - Level 0: bandit/level0.md
    - Level 1: bandit/level1.md
    - Level 2: bandit/level2.md
    - Level 3: bandit/level3.md
    - Level 4: bandit/level4.md
    - Level 5: bandit/level5.md
